#
# Copyright (c) 2015-2016, Micron Technology, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#   3. Neither the name of the copyright holder nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

SHELL:=/bin/bash

CC=/opt/nec/ve/LLVM-VE-RV/bin/clang
CPP=/opt/nec/ve/LLVM-VE-RV/bin/clang
AR=/opt/nec/ve/LLVM-VE-RV/bin/llvm-ar
LD=/opt/nec/ve/bin/ld

# Default compilation flags
CFLAGS?=-O2 -fno-slp-vectorize -mllvm -llvm-loopvec=false -Xclang -load -Xclang libRV.so -mllvm -rv --target=ve-linux --std=gnu99 -Isrc -lsysve
CFLAGS+=-Wall -fPIC
CPPFLAGS+=-D_GNU_SOURCE
LDFLAGS=-fno-slp-vectorize -mllvm -llvm-loopvec=false -Xclang -load -Xclang libRV.so -mllvm -rv --target=ve-linux --std=gnu99 -Isrc -lsysve

# To turn on debug message logging
#CPPFLAGS+=-DUNVME_DEBUG

# To use identity map for DMA address # for faster submission time
# (but may cause DMA overlapping for applications with high memory usage)
#CPPFLAGS+=-DUNVME_IDENTITY_MAP_DMA

# To build the ioengine modules, specify fio directory where header files are
FIODIR:=/home/sawamoto/fio_ve

